


{
   "email":"mukesh@gmail.com",
   "password":"pass"
}
###

#########access token #######
POST http://localhost:4001/al/login
Content-Type: application/json

{
 
    "email": "mukesh@gmail.com",
    "password": "pass"

}
###
DELETE http://localhost:4001/al/logout




###
POST http://localhost:4001/al/login
Content-Type: application/json

{
   "email":"mukesh@gmail.com",
   "password":"pass"
}


###
GET http://localhost:4001/a/posts


####
POST http://localhost:4001/note/writter
Content-Type: application/json

{
    "topic":"fasdfdsdsdsadsd",
    "subject":"tefdf6sdsd5",
    "written":"this is testing 2"
    
}



###
GET http://localhost:4001/note/allSaved
 
###
PUT http://localhost:4001/note/shareWith
Content-Type: application/json

{
"_id":"614d828033c0e3baeeee9b41",
"user1":"mukesh@gmail.com"
}

###
GET http://localhost:4001/note/resources 


###
 
DELETE http://localhost:4001/note/Delete   
Content-Type: application/json

{
"_id":"614d83a5304bed57469d61f4"
 
}
